openapi: '3.0.0'
info:
  title: Rest API Application
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: User
paths:
  /api/v1/user:
    get:
      summary: method for finding user
      operationId: findUsers
      tags:
        - User
      parameters:
        - in: query
          name: userParams
          allowEmptyValue: true
          schema:
            $ref: '#/components/schemas/FindUserRequest'
      responses:
        200:
          description: all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
        404:
          description: Users not found

    post:
      summary: create new User
      operationId: createUser
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        200:
          description: Created User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'



components:
  schemas:
    FindUserRequest:
      type: object
      description: user request params
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        phone:
          type: string
    UserResponse:
      type: object
      description: User response DTO
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        phone:
          type: string
    UserCreateRequest:
      type: object
      description: user DTO
      properties:
        name:
          type: string
        phone:
          type: string


